"use strict";
var mWeight = 78;
var mHeight = 1.69;
var jWeight = 92;
var jHeight = 1.95;
var mHigherBMI = true;
mHigherBMI = (mWeight/(mHeight*mHeight) > jWeight/(jHeight*jHeight)? true : false);
console.log(`Mark weight and height is ${mWeight}kg ${mHeight}m`);
console.log(`John weight and height is ${jWeight}kg ${jHeight}m`);
console.log(`Mark's BMI is ${mWeight/(mHeight*mHeight)} and John's BMI is ${jWeight/(jHeight*jHeight)}`);
console.log(mHigherBMI? "Mark's BMI is higher than John's!" : "John's BMI is higher than Mark's!");
console.log('--------------------------------------');
mWeight = 95;
mHeight = 1.88;
jWeight = 85;
jHeight = 1.76;
mHigherBMI = true;
mHigherBMI = (mWeight/(mHeight*mHeight) > jWeight/(jHeight*jHeight)? true : false);
console.log(`Mark weight and height is ${mWeight}kg ${mHeight}m`);
console.log(`John weight and height is ${jWeight}kg ${jHeight}m`);
console.log(`Mark's BMI is ${mWeight/(mHeight*mHeight)} and John's BMI is ${jWeight/(jHeight*jHeight)}`);
console.log(mHigherBMI? "Mark's BMI is higher than John's!" : "John's BMI is higher than Mark's!");